name: Robot Framework API & UI Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Google Chrome for Selenium
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable

    - name: Start Mock API Server
      run: |
        cd mock_api
        python mock_api.py &
        sleep 5

    - name: Run Robot Framework API Tests
      run: |
        # Run API tests and save output to a specific XML file
        robot -d reports -o output-api.xml tests/api_tests.robot
      env:
        API_URL: http://127.0.0.1:5000

    - name: Run Robot Framework UI Tests
      run: |
        # Run UI tests and save output to another specific XML file
        # Ensure your variables.robot has BASE_URL pointing to the OrangeHRM UI application.
        # Remember: If BASE_URL is localhost, the OrangeHRM app must be running within CI.
        robot -d reports -o output-ui.xml tests/ui_tests.robot

    # --- NEW STEP: MERGE TEST REPORTS ---
    - name: Merge Test Reports
      # This step uses 'rebot' to combine the two individual output XMLs
      # into a single, comprehensive report.html and log.html
      run: |
        rebot --output reports/output.xml \
              --log reports/log.html \
              --report reports/report.html \
              --name "Combined Test Results" \
              reports/output-api.xml \
              reports/output-ui.xml

    - name: Upload Test Reports
      uses: actions/upload-artifact@v4
      with:
        name: robot-test-reports
        path: reports/
        retention-days: 7